import Vue from 'vue'
import { Aside, Autocomplete, Button, Carousel, CarouselItem, Col, Container, DatePicker, Dialog, Dropdown, DropdownItem, DropdownMenu, Header, Image, InputNumber, Main, Menu, MenuItem, MenuItemGroup, Pagination, Popover, Radio, Row, Submenu, Table, TableColumn } from 'element-ui'
import {Form,FormItem,Input,Message} from 'element-ui'

Vue.use(Button)
Vue.use(Form)
Vue.use(Input)
Vue.use(FormItem)
Vue.use(Col)
Vue.use(Row)
Vue.use(Image)
Vue.use(Autocomplete)
Vue.use(Carousel)
Vue.use(CarouselItem)
Vue.use(Container)
Vue.use(Header)
Vue.use(Main)
Vue.use(Menu)
Vue.use(MenuItem)
Vue.use(MenuItemGroup)
Vue.use(DropdownMenu)
Vue.use(DropdownItem)
Vue.use(Dropdown)
Vue.use(Table)
Vue.use(TableColumn)
Vue.use(Aside)
Vue.use(Submenu)
Vue.use(Radio)
Vue.use(InputNumber)
Vue.use(Pagination)
Vue.use(Dialog)
Vue.use(Popover)
Vue.use(DatePicker)
Vue.component(Message.name,Message)
Vue.prototype.$message=Message